---
title: "Homework 3"
author: "Samuel Soon"
date: "9/23/2021"
output: pdf_document
---

# Setup


```{r load}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(broom)
library(gridExtra)
library(ggplot2)
covid_raw <- fread("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv")
us <- covid_raw[covid_raw$countriesAndTerritories == 'United_States_of_America',]
us_filtered <- us[us$month %in% c(6:7),]
us_filtered$index <- rev(1:dim(us_filtered)[1]) 
fit<-lm(`Cumulative_number_for_14_days_of_COVID-19_cases_per_100000`~index, data=us_filtered)

fit.diags <- broom::augment(fit)
```

# Problem 3

```{r p3}


rvf <- ggplot(fit.diags, aes(x=.fitted, y=.resid))+
  geom_point() +
  labs(x="Fitted", y="Residuals", title="Residuals vs Fitted")
rvf


qq <- ggplot(fit.diags, aes(x=qnorm(seq(0.01,0.99,1/(nrow(fit.diags) + 1))), y=.std.resid[order(.std.resid)])) +
  geom_point() +
  labs(x="Theoretical Quantiles", y="Standardized Residuals", title="Normal QQ")
qq

sl <- ggplot(fit.diags, aes(x=.fitted, y=sqrt(abs(.std.resid))))+
  geom_point() +
  labs(x="Fitted", y="Sqrt Standardized Residuals", title="Scale-Location")

sl

rvl <- ggplot(fit.diags, aes(x=.hat, y=.std.resid))+
  geom_point() +
  labs(x="Leverage", y="Standardized Residuals", title="Residuals vs Leverage")
rvl


```
# Problem 4


```{r p4}
grid.arrange(rvf, qq, sl, rvl, ncol = 2, nrow = 2)
```


