---
title: "HW4_ssoon"
author: "Samuel Soon"
date: "10/11/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(magrittr)
library(data.table)
library(plyr)
library(reshape2)
library(knitr)
library(ggplot2)

```

# A

```{r a,warning=FALSE}
parta  <- read.delim("https://www2.isye.gatech.edu/~jeffwu/wuhamadabook/data/ThicknessGauge.dat",
                     header = TRUE, sep="\t")

# Use tidyr to separate the block into individual columns for tidying

parta <- (parta %>% separate(col=X, 
                             into = c("Part", "O1_1", "O1_2", "O2_1", "O2_2", "O3_1", "O3_2"), 
                             convert=TRUE, sep = " "))[2:nrow(parta),]

# Remove a unnecessary empty column

parta <- subset(parta, select = -c(Operator))

# Melt the dataframe so that observations are distinguished by operator and measurement

parta <- melt(parta, id.vars = "Part", value.name = "Thickness")

# Separate Operator and Measurement into 2 variables

parta <- parta %>% tidyr::extract(variable, into=c("Operator", "Measurement"),
                                  regex='([^_]+)_([^_]+)', convert=TRUE)

kable(head(parta),caption="Duplicate Measurements of Wall Parts Taken By Operators")

kable(summary(parta), caption="Summary")


sum <- aggregate(parta$Thickness, list(parta$Part, parta$Operator), FUN=mean)

sum$x = sum$x - mean(sum$x)

sum$Group.1 <- as.factor(as.numeric(sum$Group.1))

# Chose to plot a graph that showed how each wall measurement differed from average observed wall thickness.

ggplot(sum,aes(x = Group.1,y = x,group=Group.2 ,fill = Group.2)) +
  geom_bar(stat = "identity",position = "dodge") + 
  labs(x="Part", y="Residual Average Thickness", fill = "Operator",title="Residual Average Wall Thickness Measurement Per Part, Per Operator ")
```

# B

```{r b,warning=FALSE}
partb  <- read.delim("http://www2.isye.gatech.edu/~jeffwu/wuhamadabook/data/BrainandBodyWeight.dat",
                     header = TRUE, sep="\t")

# Separate data into individual columns

partb <- partb %>% separate(col=Body.Wt.Brain.Wt.Body.Wt.Brain.Wt.Body.Wt.Brain.Wt,
                            into = c("1","2","3","4","5","6"), convert=TRUE, sep = " ")

# Collapse the repeating columns into single columns containing the information we need

body <- as.vector(as.matrix(partb[,c(TRUE,FALSE)]))
brain <- as.vector(as.matrix(partb[,c(FALSE, TRUE)]))

# Remove NA values

partb <- na.omit(data.frame("Body_Wt" = body, "Brain_Wt" = brain))

kable(head(partb),caption="Brain and Body Weight for 62 Species")

kable(summary(partb), caption="Summary")

model <- lm(Body_Wt ~ Brain_Wt, partb)

# Chose scatterplot with line of best fit to display the distribution of body weight

plot(partb, main="Brain vs Body Weight",pch=19)

abline(model, col="blue")
```

# C

```{r c,warning=FALSE}
partc  <- fread("http://www2.isye.gatech.edu/~jeffwu/wuhamadabook/data/LongJumpData.dat",
                header=TRUE, sep="\t", sep2=" ", skip=-1) 

# Separate data into individual columns

partc <- partc %>% separate(`Year Long Jump Year Long Jump Year Long Jump Year Long Jump`,
                            into = c("1","2","3","4","5","6"), convert=TRUE, sep = " ")

# Collapse columns

year <- as.vector(as.matrix(partc[,c(TRUE,FALSE)]))
ljump <- as.vector(as.matrix(partc[,c(FALSE, TRUE)]))

# Remove NA

partc <- na.omit(data.frame("Year" = year, "LongJump" = ljump))

kable(head(partc),caption="Long Jump Distance by Year")

kable(summary(partc), caption="Summary")

model <- lm(LongJump ~ Year, partc)

# Chose scatterplot with line of best fit to display the potential linear relationship between year and long jump distance

plot(partc,main="Long Jump Distance vs Year", pch=19)

abline(model, col="blue")
```

# D

```{r d,warning=FALSE}
partd  <- fread("https://www2.isye.gatech.edu/~jeffwu/wuhamadabook/data/tomato.dat",
                header=FALSE, sep=" ", sep2=",", skip=-1)

# Separate each of the yield columns into 3 columns based on planting density, measurement

for(i in 2:ncol(partd)){
  name <- paste("V", i, sep="")
  
  partd <- partd %>% tidyr::extract(name, into=paste((i-1)*10000, 1:3, sep="_"),
                                    regex='([^,]+),([^,]+),([^,]+)[,]*$', convert=TRUE)
  
}

# Melt the dataframe so that yield is distinguished by variety, density, and measurement

partd <-melt(partd, value.name="Yield",variable.name= 'Density_Measure') %>% 
  rename(c("V1" =  "Variety"))

# Separate the column generated by melting into two variables

partd <- partd %>% tidyr::extract(Density_Measure, into=c("Density", "Measurement_Number"), 
                                  regex='([^_]+)_([^_]+)', convert=TRUE)


kable(head(partd),caption="Tomato Yield Based on Variety, Planting Densities")

kable(summary(partd), caption="Summary")

sum <- aggregate(partd$Yield, list(partd$Variety, partd$Density), FUN=mean)

# I chose to use a barplot to compare the mean observed crop yield between planting densities.

ggplot(sum,aes(x = Group.1,y = x,group=Group.2 ,fill = Group.2)) +
  geom_bar(stat = "identity",position = "dodge") + 
  labs(x="Tomato Variety", y="Mean Yield", fill = "Planting Density",title="Mean Crop Yield Based on Planting Density and Tomato Variety")
```


# E

```{r e,warning=FALSE}
parte  <- fread("https://www2.isye.gatech.edu/~jeffwu/wuhamadabook/data/LarvaeControl.dat",
                header=TRUE, sep=" ", sep2=" ", skip=1) 

# Use renaming to note the age groups for convenience

parte <- parte %>% rename_with( ~ paste0("1_", .x), 2:6)

parte <- parte %>% rename_with( ~ paste0("2_", .x), 7:ncol(parte))

# Melt the data to distinguish count based on age, treatment

parte <- parte %>% melt(id.vars = c("Block"), variable.name = "Age_Treatment", value.name = "Count")

# Separate the melted column into 2 variables

parte <- parte %>% tidyr::extract(Age_Treatment, into=c("Age", "Treatment"), regex='([^_]+)_([^_]+)',
                                  convert=TRUE)

parte$Age <- as.factor(parte$Age)

kable(head(parte),caption="Larvae Counts Based on Age, Treatment")

kable(summary(parte), caption="Summary")

# I chose to use a barplot that displays the count produced based on each age group across all blocks, and show how much each treatment contributed to the total count within each block.

ggplot(parte,aes(x = Block,y = Count,group=Age,fill = Age, alpha=Treatment)) +
  geom_bar(stat = "identity",position = "dodge", color="black") + 
  labs(title="Effect of Age Group and Treatment Type on Larvae Count by Block") + 
  scale_x_continuous(breaks = seq(0, 10, by = 1))
```


